<div data-mage-init='{"test":{}}' class="test_block">
    <h2><?= __("Read More Read Less Button")?></h2>
    <p>
        <?= __("Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus imperdiet, nulla et dictum interdum, nisi
        lorem egestas vitae scel")?>
        <span class="dots">...</span>
        <span class="more">
            <?= __("erisque enim ligula venenatis dolor. Maecenas nisl est, ultrices nec congue eget, auctor vitae massa. Fusce luctus vestibulum augue ut aliquet. Nunc sagittis dictum nisi, sed ullamcorper ipsum dignissim ac. In at libero sed nunc venenatis imperdiet sed ornare turpis. Donec vitae dui eget tellus gravida venenatis. Integer fringilla congue eros non fermentum. Sed dapibus pulvinar nibh tempor porta.")?>
        </span>
    </p>
    <button class="buttonRead action primary">
        <span class="readMore"><?= __("Read more")?></span>
        <span class="readLess"><?= __("Read less")?></span>
    </button>
</div>
